services:
    _defaults:
      autoconfigure: true

    Agonyz\ContaoPageSpeedInsightsBundle\Command\MakeRequestCommand:
        arguments:
            [ '@contao.framework', '@Agonyz\ContaoPageSpeedInsightsBundle\Service\Request\RequestHandler']
        tags:
            - { name: console.command }
