services:
    _defaults:
        autoconfigure: true

    Agonyz\ContaoPageSpeedInsightsBundle\Controller\PageSpeedInsightsController:
        public: true
        arguments:
          [ '@twig', '%agonyz_contao_page_speed_insights.cache_key%', '%agonyz_contao_page_speed_insights.api_key%', '@Psr\Cache\CacheItemPoolInterface', '@Agonyz\ContaoPageSpeedInsightsBundle\Service\RequestDatabaseHandler', '@Agonyz\ContaoPageSpeedInsightsBundle\Service\RequestCacheHandler' ]
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
