services:
    _defaults:
        autoconfigure: true

    Agonyz\ContaoPageSpeedInsightsBundle\Controller\PageSpeedInsightsController:
        public: true
        arguments:
          [ '@twig', '%agonyz_contao_page_speed_insights.api_key%', '@doctrine.orm.entity_manager' ]
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
