services:
    _defaults:
        autoconfigure: true

    Agonyz\ContaoPageSpeedInsightsBundle\Controller\PageSpeedInsightsController:
        public: true
        arguments:
          [ '@twig', '%agonyz_contao_page_speed_insights.api_key%', '@doctrine.orm.entity_manager', '%agonyz_contao_page_speed_insights.request_status_refresh_rate%', '@security.helper' ]
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

    Agonyz\ContaoPageSpeedInsightsBundle\Controller\RequestListController:
        public: true
        arguments:
          [ '@twig', '@doctrine.orm.entity_manager', '%agonyz_contao_page_speed_insights.request_pagination%', '@security.helper' ]
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
