services:
  _defaults:
    autoconfigure: true
    public: true

  Agonyz\ContaoPageSpeedInsightsBundle\Repository\AgonyzRequestRepository:
    tags: ['doctrine.repository_service']
    arguments: ['@doctrine']
