services:
    _defaults:
        autoconfigure: true

    Agonyz\ContaoPageSpeedInsightsBundle\Service\GetDomainUrls: ~
    Agonyz\ContaoPageSpeedInsightsBundle\Service\GetDomainResults:
        arguments:
          [ '@Agonyz\ContaoPageSpeedInsightsBundle\Service\GetDomainUrls', '%agonyz_contao_page_speed_insights.api_key%', '%agonyz_contao_page_speed_insights.request_retries%', '%agonyz_contao_page_speed_insights.pool_request_concurrency%', '@doctrine.orm.entity_manager' ]

    Agonyz\ContaoPageSpeedInsightsBundle\Service\Request\RequestHandler:
        arguments:
            ['@Agonyz\ContaoPageSpeedInsightsBundle\Service\GetDomainResults', '@doctrine.orm.entity_manager']
